Improve data loading
kalessin/japanese-address pull request #4
Opened 2023-11-18 11:31 UTC by rennerocha

- Data was outdated, so replaced the hard coded HTML with a simple scrape script that gets the latest version of the Wikipedia pages returning more accurate information of cities, towns and wards
- Instead of parsing the HTML file every time we import the library, create a script that generate automatically the dictionaries with the data needed to parse the addresses
- Applied black formatting to entire project

2023-11-18 11:35 UTC, rennerocha commented
@kalessin 
I am using my version in a project, but given that this will have a more updated list of towns and wards, it would be great if you could release a new version (maybe a `0.2` version?)
If you are not using/maintaining this library anymore, I can handle the release process given the right permission.

2023-11-21 13:10 UTC, kalessin requested changes
The changes are ok to me. Thanks!

Only a minor fix in the README seems required, as I indicated.

2023-11-21 13:10 UTC, kalessin commented on README.md
> +```bash
shouldn't be python here?

2023-11-22 11:50 UTC, kalessin approved these changes
I will do that minimal change I asked.

2023-11-22 11:51 UTC, merged

2023-11-22 12:10 UTC, kalessin commented
hi @rennerocha much thanks for the changes! they are excellent. I just released version 0.2 with your changes.